name:                AdventOfCode2022
version:             0.1.0.0
github:              "borisskert/AdventOfCode2022"
license:             BSD3
author:              "Boris Skert"
maintainer:          "boris.skert@gmail.com"
copyright:           "2022 Boris Skert"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/borisskert/AdventOfCode2022#readme>

dependencies:
- base >= 4.7 && < 5
- stopwatch == 0.1.0.*
- clock == 0.8.*
- split == 0.2.3.*
- containers == 0.6.5.*
- regex-with-pcre == 1.1.0.*
- pcre-heavy == 1.0.0.*
- parsec == 3.1.14.*
- range == 0.3.0.*

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  AdventOfCode2022-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode2022

tests:
  AdventOfCode2022-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode2022
    - hspec == 2.7.10
